//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.21 at 10:30:52 AM PDT 
//


package gov.nasa.podaac.distribute.subscriber.cache;

import javax.xml.bind.annotation.XmlRegistry;
import gov.nasa.podaac.distribute.subscriber.cache.ObjectFactory;
import gov.nasa.podaac.distribute.subscriber.cache.SubscriberCache;
import gov.nasa.podaac.distribute.subscriber.cache.SubscriberCache.Granule;
import gov.nasa.podaac.distribute.subscriber.cache.SubscriberCache.Granule.Files;
import gov.nasa.podaac.distribute.subscriber.cache.SubscriberCache.Granule.Files.File;
import gov.nasa.podaac.distribute.subscriber.cache.SubscriberCache.Granule.GranuleInfo;
import gov.nasa.podaac.distribute.subscriber.cache.SubscriberCache.Granule.References;
import gov.nasa.podaac.distribute.subscriber.cache.SubscriberCache.Granule.References.Reference;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nasa.podaac.distribute.subscriber.cache package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nasa.podaac.distribute.subscriber.cache
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link File }
     * 
     */
    public File createSubscriberCacheGranuleFilesFile() {
        return new File();
    }

    /**
     * Create an instance of {@link Granule }
     * 
     */
    public Granule createSubscriberCacheGranule() {
        return new Granule();
    }

    /**
     * Create an instance of {@link GranuleInfo }
     * 
     */
    public GranuleInfo createSubscriberCacheGranuleGranuleInfo() {
        return new GranuleInfo();
    }

    /**
     * Create an instance of {@link SubscriberCache }
     * 
     */
    public SubscriberCache createSubscriberCache() {
        return new SubscriberCache();
    }

    /**
     * Create an instance of {@link References }
     * 
     */
    public References createSubscriberCacheGranuleReferences() {
        return new References();
    }

    /**
     * Create an instance of {@link Files }
     * 
     */
    public Files createSubscriberCacheGranuleFiles() {
        return new Files();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createSubscriberCacheGranuleReferencesReference() {
        return new Reference();
    }

}
